name: Feature Request
description: Request a new feature for angular-proto

body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: The type of feature you are requesting
      options:
        - New Primitive
        - New Core Behavior
        - Enhancement to Existing Primitive
        - Enhancement to Existing Behavior
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve
    validations:
      required: false
